export const fieldGroups = [
  {
    label: "Tier and Category",
    fields: ["tierCategory"],
  },
  {
    label: "Certificate of sponsorship status",
    fields: [
      "sponsorLicenceNumber",
      "sponsorName",
      "certificateNumber",
      "currentStatus",
      "statusDate",
      "dateAssigned",
      "expiryDate",
      "sponsorshipWithdrawn",
      "sponsorNote",
    ],
  },
  {
    label: "Personal Information",
    fields: [
      "familyName",
      "givenNames",
      "nationality",
      "placeOfBirth",
      "countryOfBirth",
      "dateOfBirth",
      "gender",
      "countryOfResidence",
    ],
  },
  {
    label: "Passport or travel document",
    fields: [
      "passportNumber",
      "passportIssueDate",
      "passportExpiryDate",
      "passportIssuePlace",
    ],
  },
  {
    label: "Current home address",
    fields: [
      "homeAddress",
      "homeCity",
      "homeProvince",
      "homePostcode",
      "homeCountry",
    ],
  },
  {
    label: "Identification numbers",
    fields: [
      "ukCardNumber",
      "insuranceNumber",
      "nationalIDCardNumber",
      "employeeNumber",
    ],
  },
  {
    label: "Work dates",
    fields: [
      "workStartDate",
      "workEndDate",
      "leaveReEnterRequired",
      "weeklyHours",
    ],
  },
  {
    label: "Main work address in the United Kingdom (mandatory for assignment)",
    fields: ["workAddress", "workCity", "workProvince", "workPostcode"],
  },
  {
    label: "Migrant's employment",
    fields: [
      "jobTitle",
      "jobTypeSOC",
      "jobDescription",
      "isNewEntrant",
      "grossSalary",
      "salaryPeriod",
      "onSalaryList",
      "appropriateSkillLevel",
      "maintenanceCertified",
      "atasRequired",
    ],
  },
  {
    label: "Migrant's employment - PAYE",
    fields: ["payeReferenceSupplied", "payeReference"],
  },
  {
    label: "Migrant's employment - PhD",
    fields: ["phdRequired"],
  },
];

// export const initialFormData: any = {
//   tierCategory: "Skilled Worker (New hires defined)",
//   sponsorLicenceNumber: "J26D64T49",
//   sponsorName: "MEDLEARN LTD",
//   certificateNumber: "C2G5L78843B",
//   currentStatus: "ASSIGNED",
//   statusDate: "18 March 2025",
//   dateAssigned: "18 March 2025",
//   expiryDate: "19 June 2025",
//   sponsorshipWithdrawn: "N",
//   sponsorNote: "Job Start date: 2nd April 2025 Job End date: 2nd March 2027",
//   familyName: "DUDHAT",
//   givenNames: "KENIL SANJAYBHAI",
//   nationality: "INDIA",
//   placeOfBirth: "MEDI AMRELI, GUJARAT",
//   countryOfBirth: "INDIA",
//   dateOfBirth: "03/06/2003",
//   gender: "Male",
//   countryOfResidence: "INDIA",
//   passportNumber: "W3739730",
//   passportIssueDate: "08 August 2022",
//   passportExpiryDate: "07 August 2032",
//   passportIssuePlace: "AHMEDABAD",
//   homeAddress: "B/2, SADGURU PARK,B/H SWAMINARAYAN NAGAR NIKOL ROAD",
//   homeCity: "NIKOL AHMEDABAD",
//   homeProvince: "AHMEDABAD",
//   homePostcode: "382350",
//   homeCountry: "INDIA",
//   workStartDate: "18 February 2025",
//   workEndDate: "01 November 2025",
//   leaveReEnterRequired: "N",
//   weeklyHours: "37.50",
//   workAddress: "158 Oxford Road",
//   workCity: "Oxford",
//   workProvince: "Oxford",
//   workPostcode: "OX4 2LA",
//   workCountry: "United Kingdom",
//   //
//   jobTitle: "Graphic and Multimedia designer",
//   jobType: "2142 Graphic and multimedia designers",
//   summaryofjob:
//     "The role of a Multimedia and Graphic Designer in the e-learning industry, or in other sectors, focuses on creating visually compelling content that enhances learning experiences, marketing materials, or brand communi- cations..",
//   newEntrant: "newEntrant",
//   grossSalary: "grossSalary",
//   immigrationSallery: "immigrationSallery",
//   sponsarGuidance: "sponsarGuidance",
//   maintenance: "maintenance",
//   approvalScheme: "approvalScheme",
// };

export const initialFormData = {
  tierCategory: "Skilled Worker (New hires defined)",
  sponsorLicenceNumber: "J26D64T49",
  sponsorName: "MEDLEARN LTD",
  certificateNumber: "C2G5L78843B",
  currentStatus: "ASSIGNED",
  statusDate: "18 March 2025",
  dateAssigned: "18 March 2025",
  expiryDate: "19 June 2025",
  sponsorshipWithdrawn: "N",
  sponsorNote: "Job Start date: 2nd April 2025 Job End date: 2nd March 2027",
  familyName: "DUDHAT",
  givenNames: "KENIL SANJAYBHAI",
  nationality: "INDIA",
  placeOfBirth: "MEDI AMRELI, GUJARAT",
  countryOfBirth: "INDIA",
  dateOfBirth: "03/06/2003",
  gender: "Male",
  countryOfResidence: "INDIA",
  passportNumber: "W3739730",
  passportIssueDate: "08 August 2022",
  passportExpiryDate: "07 August 2032",
  passportIssuePlace: "AHMEDABAD",
  homeAddress: "B/2, SADGURU PARK,B/H SWAMINARAYAN NAGAR NIKOL ROAD",
  homeCity: "NIKOL AHMEDABAD",
  homeProvince: "AHMEDABAD",
  homePostcode: "382350",
  homeCountry: "INDIA",
  workStartDate: "18 February 2025",
  // Note: Sponsor note has different dates, using these ones from 'Work dates' section
  workEndDate: "01 November 2025", // Note: Sponsor note has different dates, using these ones from 'Work dates' section
  leaveReEnterRequired: "N",
  weeklyHours: "37.50",
  workAddress: "158 Oxford Road",
  workCity: "Oxford",
  workProvince: "Oxfordshire",
  workPostcode: "OX4 2LQ",
  jobTitle: "Graphic and Multimedia designer",
  jobTypeSOC: "2142 Graphic and multimedia designers",
  jobDescription:
    "The role of a Multimedia and Graphic Designer in the e-learning industry, or in other sectors, focuses on creating visually compelling content that enhances learning experiences, marketing materials, or brand communications..",
  isNewEntrant: "Y",
  grossSalary: "30960.00",
  salaryPeriod: "Year",
  onSalaryList: "Y",
  appropriateSkillLevel: "Y",
  maintenanceCertified: "Y",
  atasRequired: "N",
  payeReferenceSupplied: "Y",
  payeReference: "120/SE13912",
  phdRequired: "N",
  //
  ukCardNumber: "",
  insuranceNumber: "",
  nationalIDCardNumber: "",
  employeeNumber: "",
};
